// Login action 
export const LOGIN_REQUESTING = 'LOGIN_REQUESTING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_REQUESTING = 'REGISTER_REQUESTING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const TYPE_ISEND = 'TYPE_ISEND';
export const LIST_USER = 'LIST_USER';
// language
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

export const SEND_REQUEST = 'SEND_REQUEST';
export const SEND_REQUEST_SUCCESS = 'SEND_REQUEST_SUCCESS';
export const SEND_REQUEST_FAILURE = 'SEND_REQUEST_FAILURE';

// loading
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

//forgot password
export const PASSWORD_REQUESTING = 'PASSWORD_REQUESTING';
export const MAIL_SUCESS = 'MAIL_SUCESS';
export const MAIL_FAIL = 'MAIL_FAIL';

// get Grammar with id
export const GET_GRAMMAR = 'GET_GRAMMAR';
export const GET_GRAMMAR_SUCCESS = 'GET_GRAMMAR_SUCCESS';
export const GET_GRAMMAR_FAIL = 'GET_GRAMMAR_FAIL';

// get all grammar 
export const GET_ALL_GRAMMAR = 'GET_ALL_GRAMMAR';
export const GET_ALL_GRAMMAR_SUCCESS = 'GET_ALL_GRAMMAR_SUCCESS';
export const GET_LIST_GRAMMAR_LEVEL_SUCCESS = 'GET_LIST_GRAMMAR_LEVEL_SUCCESS';

// get comment
export const GET_LIST_COMMENT = 'GET_LIST_COMMENT';
export const GET_LIST_COMMENT_REQUEST = 'GET_LIST_COMMENT_REQUEST';

//notification
export const GET_NOTIFI = 'GET_NOTIFI';
export const GET_NOTIFI_SUCCESS = 'GET_NOTIFI_SUCCESS';

// word
export const WORD = 'WORD';
export const ALL_WORD = 'ALL_WORD';
export const ALL_HIRA = 'ALL_HIRA';
export const ALL_KANJI = 'ALL_KANJI';
export const ALL_MEAN = 'ALL_MEAN';
export const ALL_REVERSE = 'ALL_REVERSE';
export const ALL_MEMERIZE = 'ALL_MEMERIZE';
export const ALL_NOTMEMERIZE = 'ALL_NOTMEMERIZE';
export const ALL_LIKE = 'ALL_LIKE';
export const GET_LIST_WORD_LEVEL_SUCCESS = 'GET_LIST_WORD_LEVEL_SUCCESS';

export const GET_LIST_WORD_REQUEST = 'GET_LIST_WORD_REQUEST';
export const GET_LIST_WORD_SUCCESS = 'GET_LIST_WORD_SUCCESS';

// question grammar 
export const GET_QUESTION_REQUEST = 'GET_QUESTION_REQUEST';
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS';

//flashcard
export const WORD_FLASHCARD_BEFORE = 'WORD_FLASHCARD_BEFORE';
export const MEAN_FLASHCARD_BEFORE = 'MEAN_FLASHCARD_BEFORE';
export const SPELL_FLASHCARD_BEFORE = 'SPELL_FLASHCARD_BEFORE';
export const WORD_FLASHCARD_AFTER = 'WORD_FLASHCARD_AFTER';
export const MEAN_FLASHCARD_AFTER = 'MEAN_FLASHCARD_AFTER';
export const SPELL_FLASHCARD_AFTER = 'SPELL_FLASHCARD_AFTER';
export const IMAGE_FLASHCARD_AFTER = 'SPELL_FLASHCARD_AFTER';
export const EXAMPLE_FLASHCARD_AFTER = 'EXAMPLE_FLASHCARD_AFTER';
export const MEANEXAMPLE_FLASHCARD_AFTER = 'MEANEXAMPLE_FLASHCARD_AFTER';

// word comment 
export const GET_LIST_WORD_COMMENT_REQUEST = 'GET_LIST_WORD_COMMENT_REQUEST';
export const GET_LIST_WORD_COMMENT = 'GET_LIST_WORD_COMMENT';

// level n5, n4, n3, n2
export const GET_LIST_N5 = 'GET_LIST_N5';
export const GET_LIST_N4 = 'GET_LIST_N4';
export const GET_LIST_N3 = 'GET_LIST_N3';
export const GET_LIST_N2 = 'GET_LIST_N2';

// test word
export const GET_N5_TEST = 'GET_N5_TEST';
export const GET_N4_TEST = 'GET_N4_TEST';
export const GET_N3_TEST = 'GET_N3_TEST';
export const GET_N2_TEST = 'GET_N2_TEST';

// type question
export const GET_CHOOSE_QUESTION = 'GET_CHOOSE_QUESTION';
export const GET_JOIN_QUESTION = 'GET_JOIN_QUESTION';

// choose list word test 
export const GET_ALL_WORD_TEST = 'GET_ALL_WORD_TEST';
export const GET_MEMERIZE_WORD_TEST = 'GET_MEMERIZE_WORD_TEST';
export const GET_NOTMEMERIZE_WORD_TEST = 'GET_NOTMEMERIZE_WORD_TEST';
export const GET_LIKE_TEST = 'GET_LIKE_TEST';

// noti
export const NOTI_10BEFORE = 'NOTI_10BEFORE';
export const NOTI_30BEFORE = 'NOTI_30BEFORE';
export const NOTI_1HOURBEFORE = 'NOTI_1HOURBEFORE';
export const NOTI_1DAYBEFORE = 'NOTI_1DAYBEFORE';
export const MAIL_NOTI = 'MAIL_NOTI';
export const IPHONE_NOTI = 'IPHONE_NOTI';


// kanji
export const GET_LIST_KANJI_REQUEST = 'GET_LIST_KANJI_REQUEST';
export const GET_LIST_KANJI_SUCCESS = 'GET_LIST_KANJI_SUCCESS';
export const GET_LIST_KANJI_LEVEL_SUCCESS = 'GET_LIST_KANJI_LEVEL_SUCCESS';

export const ALL_KANJI_LIST = 'ALL_KANJI_LIST';
export const ALL_MEMERIZE_KANJI = 'ALL_MEMERIZE_KANJI';
export const ALL_NOTMEMERIZE_KANJI = 'ALL_NOTMEMERIZE_KANJI';
export const ALL_LIKE_KANJI = 'ALL_LIKE_KANJI';


export const GET_LIST_KANJI_COMMENT_REQUEST = 'GET_LIST_KANJI_COMMENT_REQUEST';
export const GET_LIST_KANJI_COMMENT_SUCCESS = 'GET_LIST_KANJI_COMMENT_SUCCESS';

// schedule
export const GET_SCHEDULE_REQUEST = 'GET_SCHEDULE_REQUEST';
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS';

// vocabulary
export const GET_LIST_VOCABULARY_REQUEST = 'GET_LIST_VOCABULARY_REQUEST';
export const GET_LIST_VOCABULARY_SUCCESS = 'GET_LIST_VOCABULARY_SUCCESS';


//post
export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';

export const WORD_VOCABULARY = 'WORD_VOCABULARY';